Olio 13 generate query schema
Smart-Highschool-Ace/Olio2_API pull request #18
Opened 2021-02-22 20:10 UTC by hanbin8269

- portfolio, project 모델의 하나 조회, 모두 조회 등 기본 쿼리 작성
- skillSearch, nameSearch, explore, emailSearch 쿼리 틀만 작성
- search쿼리 는 명세서가 완성되지 않아 미작성

2021-02-23 06:02 UTC, sunrabbit123 approved these changes

2021-02-24 12:05 UTC, hmoon630 requested changes
몇몇 부분에서 수정이 필요할 것 같아요 😓 확인해 보시고 이해 안되는 부분이 있다면 추가로 코멘트 달아주세요 :D

2021-02-24 12:05 UTC, skyuecx0630 commented on src/schema/types/Query.ts
> +    t.list.field("myProjects", q.myProjects);
이 부분은 user를 통해 접근할 수 있기 때문에, 중복될 수 있다고 생각해요. 
```
query {
  user(id: 1) {
    projects
  }
}
```

2021-02-24 12:05 UTC, skyuecx0630 commented on src/schema/types/models/Project.ts
> +});
이 부분은 아마 포트폴리오에서 나의 프로젝트를 불러올 때 사용되는 것 같은데, 이미 Portfolio에 존재하는 내용이에요 😅 이 부분은 지워도 무방할 것 같아요.

2021-02-24 12:05 UTC, hmoon630 commented on src/schema/types/models/Search.ts
> +});
Search는 object가 아닌 query가 어울리는 것 같아요. portfolio나 project 같은 것들이 Object 이고, 검색의 경우는 이러한 object를 찾는 행위이기 때문에 query로 옮기는 것이 맞다고 생각해요.

2021-02-24 12:05 UTC, hmoon630 commented on src/schema/types/queries/Portfolio.ts
> +    });
resolve 함수의 내용은 service에 있는 함수를 이용하면, 코드의 재활용성을 높이고, 이 resolve 함수가 무엇을 반환하는지 더욱 알기 쉽게 해줄거에요.
```
import { PortfolioService } from 'service'

return await PortfolioService.getPortfolio(root.id)
```
간단하게 의사 코드로만 작성해 보았어요 :D

2021-02-24 12:05 UTC, hmoon630 commented on src/schema/types/queries/Project.ts
> +  },
위에 코멘트와 동일한 맥락의 부분이에요 :) 이와 비슷한 다른 부분 들도 신경써서 수정해 주시길 바랄게요

2021-02-27 14:02 UTC, hanbin8269 commented on src/schema/types/Query.ts
> +    t.list.field("myProjects", q.myProjects);
https://www.notion.so/MyProjects-572ee4bbe8ac4ff391c47e79d92b7c77
API 명세서에 order 필드가 명시되어 있어서 따로 필요하다고 생각했어요

2021-02-27 14:02 UTC, hanbin8269 commented on src/schema/types/models/Project.ts
> +});
위 코멘트 쿼리의 return Form 이에요. 위의 쿼리가 필요하다면 지워서는 안되는 부분이에요.

2021-02-27 15:41 UTC, hanbin8269 commented on src/schema/types/models/Search.ts
> +});
이 부분 또한 쿼리의 리턴 폼이에요. 인터페이스 타입에 대해 몰라서 리턴 폼을 이런 식으로 만들었어요. 
이 부분을 지우고 `\types\queries\Search.ts` 위치에 인터페이스 타입을 만들어서 수정할게요.

2021-02-27 15:41 UTC, hanbin8269 commented on src/schema/types/queries/Portfolio.ts
> +    });
확인했습니다.

2021-02-27 15:41 UTC, hanbin8269 commented on src/schema/types/queries/Project.ts
> +  },
확인했습니다 :)

2021-02-28 05:48 UTC, seojinsarejj approved these changes

2021-03-02 09:14 UTC, hmoon630 approved these changes

2021-03-02 09:15 UTC, merged