Olio 25 project mutation resolver
Smart-Highschool-Ace/Olio2_API pull request #20
Opened 2021-03-03 23:04 UTC by seojinsarejj

2021-03-04 09:26 UTC, hmoon630 requested changes

2021-03-04 09:26 UTC, hmoon630 commented on src/service/project.ts
> +import { fieldAuthorizePlugin } from "nexus";
이 줄은 지워도 될 것 같네요 :D
```suggestion
```

2021-03-04 09:26 UTC, hmoon630 commented on src/service/project.ts
> +  await prisma.proejctLike.deleteMany({
하나만 지우는 것이기 때문에 굳이 deleteMany를 쓸 이유는 없겠네요 :D
```suggestion
  await prisma.proejctLike.delete({
```

2021-03-04 09:26 UTC, hmoon630 commented on src/schema/types/mutations/Project.ts
> +}
interface들은 전부 src/interface 폴더로 옮겨주세요 :D 여기보단 interface 끼리 모아놓는 것이 보기 좋을 것 같아요

2021-03-09 07:09 UTC, sunrabbit123 reviewed
PR의 이유인 `Project Mutation`과 상관이 없는 타 파일들이 이전 버전으로 복구되는 경향이 있으니 main 브랜치를 한번 더 pull 부탁드려요 :D

2021-03-09 07:09 UTC, sunrabbit123 commented on src/schema/types/mutations/Project.ts
> +  resolve: async (_: any, args: any, ctx: any) => {
해당 `resolve`에  `ctx`를 사용 안하니 `_`처리 하는 것이 좋다고 생각하는데, 어떻게 생각하세요?
```suggestion
  resolve: async (_: any, args: any, __: any) => {
```

2021-03-09 07:09 UTC, sunrabbit123 commented on src/schema/types/mutations/Project.ts
> +  resolve: async (_: any, args: any, ctx: any) => {
여기도 `ctx`가 사용이 안되니, `__`처리 하는것이 좋다고 생각되네요
```suggestion
  resolve: async (_: any, args: any, __: any) => {
```

2021-03-15 11:49 UTC, hmoon630 approved these changes

2021-03-17 23:11 UTC, sunrabbit123 approved these changes

2021-03-22 00:20 UTC, merged