Olio 24 user mutation resolver
Smart-Highschool-Ace/Olio2_API pull request #21
Opened 2021-03-04 08:29 UTC by icefirebear

- userCreate resolver 구현
- userUpdate resolver 구현
- userDelete resolver 구현

2021-03-04 12:13 UTC, hmoon630 requested changes

2021-03-04 12:13 UTC, skyuecx0630 commented on src/schema/types/mutations/User.ts
> +}
인터페이스들은 모두 src/interface로 옮겨주세요. interface 폴더가 좀 더 어울리는 것 같네요 :D

2021-03-04 12:13 UTC, skyuecx0630 commented on src/schema/types/mutations/User.ts
> +}
이것도 유의해서 모두 옮겨주세요 :D

2021-03-04 12:13 UTC, hmoon630 commented on src/service/user.ts
> +        password: Joi.string().required(),
이메일은 email로 변수 이름 통일 해주세요 😄

2021-03-12 06:45 UTC, icefirebear commented on src/schema/types/mutations/User.ts
> +}
네네 😊 확인했습니다😃😃

2021-03-12 06:46 UTC, icefirebear commented on src/service/user.ts
> +        password: Joi.string().required(),
네 변경했습니다😊😊

2021-03-12 07:20 UTC, sunrabbit123 reviewed
코드를 읽으면서 몇가지를 발견하였는데, 이에 대해서 어떻게 생각하실지는 잘 모르겠어서 코멘트 달아놨습니다.

2021-03-12 07:20 UTC, sunrabbit123 commented on src/schema/types/models/User.ts
> +            resolve: (root) => {
```suggestion
            resolve: (root, _, __) => {
```
나머지 인자값도 들어오지만, 사용하지않는다는 의미로 이렇게 적어주는 것이 좋다고 생각합니다.

2021-03-12 07:20 UTC, sunrabbit123 commented on src/schema/types/models/User.ts
> +import { interfaceType, objectType } from "nexus";
```suggestion
import { objectType } from "nexus";
```

사용하지 않는 것은 import를 해제 하는 것이 좋다고 생각됩니다

2021-03-12 07:20 UTC, sunrabbit123 commented on src/schema/types/mutations/User.ts
> +    resolve: async (_: any, args: any, ctx: any) => {
```suggestion
    resolve: async (_: any, args: any, __ : any) => {
```

`ctx`를 사용하지 않으니, `__`로 바꾸는 것이 좋지 않을까 생각됩니다.

2021-03-12 07:20 UTC, sunrabbit123 commented on src/schema/types/mutations/User.ts
> +    resolve: async (_: any, user: UserUpdateArgs, ctx: any) => {
```typescript
    import { context } from "context";



    resolve: async (_: any, user: UserUpdateArgs, ctx: context) => {
```

`ctx`의 타입을 지정해주는 것이 좋다고 생각됩니다.

2021-03-12 09:32 UTC, icefirebear commented on src/schema/types/models/User.ts
> +            resolve: (root) => {
아 구별하기 더 쉽겠네요 좋습니다😃😃

2021-03-12 11:03 UTC, icefirebear commented on src/schema/types/mutations/User.ts
> +    resolve: async (_: any, user: UserUpdateArgs, ctx: any) => {
테스트 후 type annotation 적용하도록 하겠습니다👍👍

2021-03-12 11:59 UTC, icefirebear reviewed
Good😃😃😃😃😃😃

2021-03-12 12:53 UTC, hmoon630 reviewed
필요없는 console.log만 수정하면 되겠네요:D

2021-03-12 12:53 UTC, hmoon630 commented on src/service/user.ts
> +import { Prisma, PrismaClient, School } from "@prisma/client";
불필요한 import를 지웠어요 :D
```suggestion
import { PrismaClient } from "@prisma/client";
```

2021-03-12 12:53 UTC, hmoon630 commented on src/service/user.ts
> +    console.log(School[user.school]);
불필요한 console.log를 지웠어요 :D
```suggestion

```

2021-03-12 15:17 UTC, sunrabbit123 reviewed
문득 떠올라서 코멘트 남기고 갑니다, 저는 이렇게 생각하는데, 어떻게 생각하시나요?

2021-03-12 15:17 UTC, sunrabbit123 commented on src/service/user.ts
> +      email: user.email,
user.email를 그대로 받아들여서 실행하기전에, 이메일의 형식이 맞는지 검사하는 구문이 있으면 좋지않을까 생각합니다

2021-03-12 15:20 UTC, icefirebear commented on src/service/user.ts
> +      email: user.email,
해당 구문은 checkEmail mutation에서 형식검사를 포함해 학교계정검사와 중복검사를 하고 있어서 해당 모듈에서는 검사를 굳이 진행하지 않았습니다😊

2021-03-12 15:36 UTC, sunrabbit123 commented on src/service/user.ts
> +  return await prisma.user.create({
기능명세서에 명시되어있는 거처럼 빈 포트폴리오 생성도 추가해줬으면 좋겠다고 생각합니다

2021-03-13 01:04 UTC, icefirebear commented on src/service/user.ts
> +  return await prisma.user.create({
제가 확인을 못 했네요 추가하겠습니다😃😃

2021-03-13 01:15 UTC, icefirebear commented on src/service/user.ts
> +  return await prisma.user.create({
아직 Project Service가 구현이 되지 않아서 #20 Olio 25 project mutation resolver PR merge되면 추가하도록 하겠습니다😊😊😊

2021-03-15 02:41 UTC, merged