Olio 19 portfolio resolver [UPDATE]
Smart-Highschool-Ace/Olio2_API pull request #26
Opened 2021-03-17 14:09 UTC by sunrabbit123

기존에 있던 버그들을 수정하였습니다.
제공되지 않던 타입들을 제공하게 수정하였습니다.

2021-03-19 01:32 UTC, hmoon630 requested changes
아래의 코멘트 확인해주세요 :D

2021-03-19 01:32 UTC, hmoon630 commented on src/schema/types/inputs/Portfolio.ts
> +    t.nonNull.string("name"), t.nonNull.int("level");
definition 적는 부분은 다른 코드들은 ;으로 구분되어 있는데 이 파일만 ,로 구분되어 있네요. 다른 부분과 맞추면 더 좋을 것 같아요;D
```suggestion
    t.nonNull.string("name");
    t.nonNull.int("level");
```

2021-03-19 01:32 UTC, hmoon630 commented on src/schema/types/models/Portfolio.ts
>      t.int("order");
기존에 있던 대로 type을 project로 두어야 할 것 같아요. 그래야 project의 정보들을 불러올 수 있거든요 :D
```suggestion
    t.field("project", {
      type: "Project",
    });
    t.int("order");
```

2021-03-19 01:32 UTC, hmoon630 commented on src/schema/types/models/Portfolio.ts
> +    t.string("name");
기존의 Skill type을 두어야 skill table에 있는 정보를 이용해서 사용할 수 있을거에요. gql로 불러올 때는 
```
skill {
  name
}
```
처럼 불러오면 돼요:D
```suggestion
    t.field("skill", {
      type: "Skill",
    });
```

2021-03-19 01:32 UTC, hmoon630 commented on src/schema/types/mutations/Portfolio.ts
> +import { PortfolioService, UserService } from "service";
불필요한 import :)
```suggestion
import { PortfolioService } from "service";
```

2021-03-19 01:32 UTC, hmoon630 commented on src/service/portfolio.ts
> +
이런 함수는 util에 모아서 관리하면 될거 같아요 :D 다른 부분에서도 충분히 사용 될수 있으니까요

2021-03-19 01:32 UTC, hmoon630 commented on src/service/portfolio.ts
> +  updateArgs.skils = updateArgs.skils || [];
skils 오타가 있네요.. :( skills로 수정해 주시면 좋을 것 같아요

2021-03-20 04:54 UTC, sunrabbit123 commented on src/schema/types/models/Portfolio.ts
> +    t.string("name");
일반적인 스키마가 아닌, 넥서스 오브젝트 타입이기에 그렇게 작성할 경우 null만 반환하더라고요

2021-03-20 13:14 UTC, sunrabbit123 commented on src/schema/types/models/Portfolio.ts
>      t.int("order");
다음과 같이 수정한 후 실행을 한 결과, `skill`처럼 `null`이 돌아올 뿐이였습니다.
그래서 프로젝트 관련된 값들을 resolve로 작성하는 것이 나을 것 같다고 생각합니다.

어떻게 생각하시나요? 만약 긍정적으로 검토한다면 어떤 값들이 추가 됐으면 하는지 말씀드리면 좋겠습니다.

2021-03-21 23:48 UTC, hmoon630 commented on src/schema/types/models/Portfolio.ts
>      t.int("order");
해당 파일 32번째 라인 보니 타입 지정이 잘못되어있었네요! 이 부분만 수정하면 바로 될거 같습니다 :)
```
    t.list.field("projects", {
      type: "Project",
      resolve: async (root, _, __) => {
        return (await PortfolioService.getPortfolio(root.id)).PortfolioProject;
      },
    });
```

2021-03-22 02:24 UTC, sunrabbit123 commented on src/schema/types/models/Portfolio.ts
>      t.int("order");
제가 실수를 했었네요, 죄송합니다.
코멘트 내용을 반영하여 커밋하였습니다.

2021-03-22 02:24 UTC, sunrabbit123 commented on src/schema/types/models/Portfolio.ts
> +    t.string("name");
제가 실수를 했었네요, 죄송합니다.
코멘트 내용을 반영하여 커밋하였습니다.

2021-03-23 03:14 UTC, hmoon630 approved these changes

2021-03-23 03:14 UTC, hmoon630 commented on src/util/date.ts
> +  // 입력 데이터가 스트링이지만, service/portfolio에서 사용 시 Date로 타입이 뜨기에 any로 작성함
moment.js 라이브러리를 쓰면 다음의 코드와 같이 더욱 간단한 포매팅을 할 수 있어요. 
```
var date = new Date();
var formattedDate = moment(date).format('YYYYMMDD');
```

2021-03-23 07:07 UTC, sunrabbit123 commented on src/util/date.ts
> +  // 입력 데이터가 스트링이지만, service/portfolio에서 사용 시 Date로 타입이 뜨기에 any로 작성함
moment.js는 버전 관리 및, 추후 업데이트가 없을 예정의 모듈이면서, 무게가 많이 무겁기때문에, day.js로 대체하였습니다.

2021-03-24 12:10 UTC, seojinsarejj approved these changes

2021-03-24 13:55 UTC, merged