[UPDATE] README.md
Smart-Highschool-Ace/Olio2_API pull request #34
Opened 2021-04-13 13:42 UTC by hmoon630

README.md 파일에 내용을 추가하였습니다.

2021-04-13 13:56 UTC, sunrabbit123 commented on README.md
> +SALT="0LI0-3"
Salt를 공개해도 되는지 잘 모르겠네요. 다른분들의 의견이 궁금합니다.

2021-04-13 13:58 UTC, sunrabbit123 requested changes

2021-04-13 13:58 UTC, sunrabbit123 commented on README.md
> +```sh
```suggestion
```ini
```
sh는 쉘 스크립트를 의미하고, ini는 설정파일을 의미하기때문에, ini가 더 어울리지않을까 싶습니다.
다른분들의 의견은 어떤가요??

2021-04-13 14:04 UTC, hmoon630 commented on README.md
> +```sh
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
github에서 제공하는 code block의 syntax highlighting은 linguist를 이용하는데, .env 파일은 Shell의 목록에 포함되어 있어서 위와 같이 사용했습니다.

2021-04-13 14:06 UTC, hmoon630 commented on README.md
> +SALT="0LI0-3"
실제 프로덕션 환경에 올릴 때는 환경변수를 모두 변경하고 올려야 하기 때문에 상관 없을 것 같습니다.

2021-04-13 14:06 UTC, sunrabbit123 commented on README.md
> +SALT="0LI0-3"
답변 감사합니다 :D

2021-04-13 14:06 UTC, sunrabbit123 commented on README.md
> +```sh
답변 감사합니다 :D

2021-04-13 14:07 UTC, sunrabbit123 approved these changes

2021-04-21 11:58 UTC, icefirebear approved these changes

2021-04-21 11:58 UTC, merged