Olio 32 portfolio project search
Smart-Highschool-Ace/Olio2_API pull request #37
Opened 2021-04-24 14:53 UTC by sunrabbit123

![image](https://user-images.githubusercontent.com/64676070/115962846-392eb700-a558-11eb-8406-b1be34cbbdbe.png)
![image](https://user-images.githubusercontent.com/64676070/115962849-3cc23e00-a558-11eb-81b3-effcf0c1cabf.png)

add:
portfolio search(using contains)
project search(using contains)

2021-04-25 23:07 UTC, hanbin8269 approved these changes

2021-04-25 23:21 UTC, hmoon630 requested changes
모델을 정의하는 부분에서 수정하면 좋을 것 같은 부분을 좀 찾아봤어요. 확인해주세요 😄

2021-04-25 23:21 UTC, hmoon630 commented on src/schema/types/models/Search.ts
> +});
두 가지 모두 새로운 모델 정의를 만들기 보다는, 어차피 각각 Portfolio모델과 Project 모델이 겹치기 때문에 기존에 있는 모델을 사용하는 것으로 바꾸어주면 될 것 같아요.

2021-04-25 23:21 UTC, hmoon630 commented on src/schema/types/queries/Search.ts
> +};
타입은 다음과 같이 바꾸고, 이에 맞추어서 resolve 함수도 변경이 필요할 것 같아요. User를 불러오는 것이 아닌, User의 Portfolio를 불러와야 하니까요.
```suggestion
export const portfolioSearch = {
  type: "Portfolio",
  args: {
    name: nonNull(stringArg()),
  },
  resolve: async (_: any, args: any, __: any) => {
    return await UserService.findUserByName(args.name);
  },
};
```

2021-04-25 23:21 UTC, hmoon630 commented on src/schema/types/queries/Search.ts
> +};
여기는 타입만 바꾸면 되겠네요 :D
```suggestion
export const projectSearch = {
  type: "Project",
  args: {
    name: nonNull(stringArg()),
  },
  resolve: async (_: any, args: any, __: any) => {
    return await ProjectService.findProjectByName(args.name);
  },
};
```

2021-04-26 01:08 UTC, sunrabbit123 commented
![image](https://user-images.githubusercontent.com/64676070/116016325-3eceee80-a677-11eb-952b-4bb7d84d6b8f.png)
![image](https://user-images.githubusercontent.com/64676070/116016334-45f5fc80-a677-11eb-95d0-871a778558cd.png)

2021-04-27 02:10 UTC, hmoon630 approved these changes

2021-04-27 03:54 UTC, seojinsarejj approved these changes

2021-04-27 03:55 UTC, merged