Olio 15 user login
Smart-Highschool-Ace/Olio2_API pull request #5
Opened 2021-02-18 10:39 UTC by sunrabbit123

리뷰 후 피드백 부탁드려요 :)

2021-02-18 10:52 UTC, hmoon630 requested changes
아래 내용들 확인해 보세용

2021-02-18 10:52 UTC, hmoon630 commented on src/service/user.ts
> +        await prisma.user.findMany({
유저 한명을 찾을 떄에는 findFirst 함수를 쓰면 됩니다
```suggestion
        await prisma.user.findFirst({
```

2021-02-18 10:52 UTC, hmoon630 commented on src/service/user.ts
> +        const token = { token : generateToken({"email" : email})};
token에 담는 값은 userId를 담기로 하였는데, 이메일 대신 id를 넣어주세용
```suggestion
        const token = { token : generateToken({"userId" : user.id})};
```

2021-02-18 10:52 UTC, hmoon630 commented on src/service/user.ts
> +    }
404 보다는 잘못된 요청을 나타내는 400이 더 나아보여요. 그리고 error는 사용자가 알아볼 수 있도록 한국어로 메시지를 적어주는 것도 좋겠네요

2021-02-18 10:52 UTC, hmoon630 commented on src/service/user.ts
> +}
Line Ending이 추가 되지 않은걸로 보아 Prettier를 적용하지 않은거 같은데, 적용 해주면 좋겠어요. 

이 부분은 개발 가이드라인에 추가 해놓을게요 :D

2021-02-18 10:52 UTC, hmoon630 commented on src/util/hash.ts
> +    return crypto.createHash('sha512').update(password + salt).digest('base64');
salt를 추가할 때에는 createHash 함수가 아닌 createHmac 함수를 사용하면 돼요.
```suggestion
    return crypto.createHmac('sha512', salt).update(password).digest('base64');
```

2021-02-18 10:52 UTC, hmoon630 commented on src/util/token.ts
> +}
email 대신 userId 값을 넣어봤어요
```suggestion
export const generateToken : Function = ( userId: Int) : String => {
    return jwt.sign(String(userId), jwtSecret);
}
```

2021-02-18 16:44 UTC, hanbin8269 approved these changes

2021-02-18 16:44 UTC, hanbin8269 commented on src/service/user.ts
> +    )[0];
```suggestion
    );
```

2021-02-18 16:44 UTC, merged

2021-02-19 08:56 UTC, sunrabbit123 commented on src/service/user.ts
> +        await prisma.user.findMany({
findOne 썼다가 에러 떠서 저리했는데 수정하겠습니다.

2021-02-19 09:33 UTC, sunrabbit123 commented on src/service/user.ts
> +    }
이 부분은 에러코드를 나타내지않고 에러임만을 표시하기 위해 에러코드부분은 삭제되었습니다